import 'package:flutter/services.dart';

final _keyNames = <LogicalKeyboardKey, String>{
  LogicalKeyboardKey.keyA: 'A',
  LogicalKeyboardKey.keyB: 'B',
  LogicalKeyboardKey.keyC: 'C',
  LogicalKeyboardKey.keyD: 'D',
  LogicalKeyboardKey.keyE: 'E',
  LogicalKeyboardKey.keyF: 'F',
  LogicalKeyboardKey.keyG: 'G',
  LogicalKeyboardKey.keyH: 'H',
  LogicalKeyboardKey.keyI: 'I',
  LogicalKeyboardKey.keyJ: 'J',
  LogicalKeyboardKey.keyK: 'K',
  LogicalKeyboardKey.keyL: 'L',
  LogicalKeyboardKey.keyM: 'M',
  LogicalKeyboardKey.keyN: 'N',
  LogicalKeyboardKey.keyO: 'O',
  LogicalKeyboardKey.keyP: 'P',
  LogicalKeyboardKey.keyQ: 'Q',
  LogicalKeyboardKey.keyR: 'R',
  LogicalKeyboardKey.keyS: 'S',
  LogicalKeyboardKey.keyT: 'T',
  LogicalKeyboardKey.keyU: 'U',
  LogicalKeyboardKey.keyV: 'V',
  LogicalKeyboardKey.keyW: 'W',
  LogicalKeyboardKey.keyX: 'X',
  LogicalKeyboardKey.keyY: 'Y',
  LogicalKeyboardKey.keyZ: 'Z',
  LogicalKeyboardKey.digit0: '0',
  LogicalKeyboardKey.digit1: '1',
  LogicalKeyboardKey.digit2: '2',
  LogicalKeyboardKey.digit3: '3',
  LogicalKeyboardKey.digit4: '4',
  LogicalKeyboardKey.digit5: '5',
  LogicalKeyboardKey.digit6: '6',
  LogicalKeyboardKey.digit7: '7',
  LogicalKeyboardKey.digit8: '8',
  LogicalKeyboardKey.digit9: '9',
  LogicalKeyboardKey.f1: 'F1',
  LogicalKeyboardKey.f2: 'F2',
  LogicalKeyboardKey.f3: 'F3',
  LogicalKeyboardKey.f4: 'F4',
  LogicalKeyboardKey.f5: 'F5',
  LogicalKeyboardKey.f6: 'F6',
  LogicalKeyboardKey.f7: 'F7',
  LogicalKeyboardKey.f8: 'F8',
  LogicalKeyboardKey.f9: 'F9',
  LogicalKeyboardKey.f10: 'F10',
  LogicalKeyboardKey.f11: 'F11',
  LogicalKeyboardKey.f12: 'F12',
  LogicalKeyboardKey.enter: 'Enter',
  LogicalKeyboardKey.numpadEnter: 'NumpadEnter',
  LogicalKeyboardKey.escape: 'Escape',
  LogicalKeyboardKey.insert: 'Insert',
  LogicalKeyboardKey.tab: 'Tab',
  LogicalKeyboardKey.backspace: 'Backspace',
  LogicalKeyboardKey.delete: 'Delete',
  LogicalKeyboardKey.space: 'Space',
  LogicalKeyboardKey.arrowLeft: 'Left',
 LogicalKeyboardKey.arrowRight: 'Right',
  LogicalKeyboardKey.arrowUp: 'Up',
  LogicalKeyboardKey.arrowDown: 'Down',
  LogicalKeyboardKey.home: 'Home',
  LogicalKeyboardKey.end: 'End',
  LogicalKeyboardKey.pageUp: 'PageUp',
  LogicalKeyboardKey.pageDown: 'PageDown',
  LogicalKeyboardKey.comma: 'Comma',
  LogicalKeyboardKey.period: 'Period',
  LogicalKeyboardKey.semicolon: 'Semicolon',
  LogicalKeyboardKey.quote: 'Quote',
  LogicalKeyboardKey.bracketLeft: 'BracketLeft',
  LogicalKeyboardKey.bracketRight: 'BracketRight',
  LogicalKeyboardKey.backslash: 'Backslash',
  LogicalKeyboardKey.slash: 'Slash',
  LogicalKeyboardKey.minus: 'Minus',
  LogicalKeyboardKey.equal: 'Equal',
  LogicalKeyboardKey.backquote: 'Backquote',
  LogicalKeyboardKey.intlBackslash: 'IntlBackslash',
};

String? shortcutKeyName(LogicalKeyboardKey key) => _keyNames[key];

LogicalKeyboardKey? parseShortcutKeyName(String name) {
  for (final entry in _keyNames.entries) {
    if (entry.value == name) return entry.key;
  }
  return null;
}

